export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS runs (
    id TEXT PRIMARY KEY,
    window_date TEXT NOT NULL,
    status TEXT NOT NULL,
    started_at TEXT NOT NULL,
    collection_completed_at TEXT,
    completed_at TEXT,
    published_at TEXT,
    total_items INTEGER NOT NULL DEFAULT 0,
    terminal_items INTEGER NOT NULL DEFAULT 0,
    successful_items INTEGER NOT NULL DEFAULT 0,
    failed_items INTEGER NOT NULL DEFAULT 0,
    deferred_items INTEGER NOT NULL DEFAULT 0,
    metadata_json TEXT NOT NULL DEFAULT '{}'
  )`,
  `CREATE TABLE IF NOT EXISTS items (
    item_key TEXT PRIMARY KEY,
    id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    source_id TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT NOT NULL,
    published_at TEXT,
    dedupe_key TEXT NOT NULL,
    normalized_item_json TEXT,
    content_status TEXT NOT NULL,
    enrichment_status TEXT NOT NULL,
    final_status TEXT NOT NULL,
    retry_count_fetch INTEGER NOT NULL DEFAULT 0,
    retry_count_enrichment INTEGER NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 0,
    carry_forward_run_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(run_id) REFERENCES runs(id),
    UNIQUE(run_id, id)
  )`,
  `CREATE TABLE IF NOT EXISTS item_contents (
    item_key TEXT PRIMARY KEY,
    raw_content TEXT,
    clean_content TEXT,
    content_length INTEGER NOT NULL DEFAULT 0,
    fetch_method TEXT,
    fetch_started_at TEXT,
    fetch_completed_at TEXT,
    fetch_duration_ms INTEGER,
    fetch_error TEXT,
    FOREIGN KEY(item_key) REFERENCES items(item_key)
  )`,
  `CREATE TABLE IF NOT EXISTS item_enrichments (
    item_key TEXT PRIMARY KEY,
    model TEXT,
    prompt_version TEXT,
    summary TEXT,
    why_it_matters TEXT,
    topics_json TEXT NOT NULL DEFAULT '[]',
    relevance_score REAL,
    relevance_bucket TEXT,
    raw_response TEXT,
    tokens_in INTEGER,
    tokens_out INTEGER,
    duration_ms INTEGER,
    created_at TEXT NOT NULL,
    FOREIGN KEY(item_key) REFERENCES items(item_key)
  )`,
  `CREATE TABLE IF NOT EXISTS item_attempts (
    id TEXT PRIMARY KEY,
    item_key TEXT NOT NULL,
    stage TEXT NOT NULL,
    attempt_number INTEGER NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    duration_ms INTEGER,
    outcome TEXT NOT NULL,
    error_message TEXT,
    FOREIGN KEY(item_key) REFERENCES items(item_key)
  )`,
  `CREATE TABLE IF NOT EXISTS digest_review_items (
    digest_date TEXT NOT NULL,
    run_id TEXT NOT NULL,
    item_key TEXT NOT NULL,
    published_at TEXT,
    title TEXT NOT NULL,
    excerpt TEXT NOT NULL,
    item_url TEXT,
    source_name TEXT,
    topic_tags_json TEXT NOT NULL,
    match_score REAL NOT NULL DEFAULT 0,
    normalized_item_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (digest_date, item_key)
  )`,
  `CREATE TABLE IF NOT EXISTS digest_item_reviews (
    item_key TEXT PRIMARY KEY,
    rating INTEGER,
    follow_up INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
] as const;
